// Artifact guides used across the editor. Exposed as a global for simplicity.
window.artifactGuides = {
    'functional-requirement': `Os Requisitos Funcionais (RF) são uma condição que o sistema deve atender, sendo requisitos que exigem ou restringem funcionalidades para o usuário.`,
    'architectural-requirement': `Os Requisitos Arquiteturais (RA), também denominados requisitos não funcionais ou de qualidade, são as propriedades que o sistema deve atender, focando em atributos de qualidade ou de negócio. Para a especificação, espera-se que um RA seja detalhado de modo a se ter como saber se foi atendido ou não, sendo necessário incluir uma forma de medição e critério de satisfação, que deve ser uma métrica objetivamente testável (nada muito subjetivo).`,
    'stakeholder': `O termo "stakeholder", traduzido para o português como "parte interessada", refere-se fundamentalmente à pessoa que tem algum interesse no sistema, podendo ser um cliente que vai comprar o sistema, o usuário final (que não necessariamente são a mesma pessoa), o gestor do time, os desenvolvedores, etc.`,
    'architectural-scenario': `Um Cenário Arquitetural é definido como a descrição de uma interação com o sistema vista do ponto de vista de uma parte interessada (stakeholder). Essa ferramenta é fundamental na "Análise Arquitetural", pois os cenários ajudam a identificar os requisitos arquiteturais, visto que cada parte interessada tem interesses diferentes no sistema. Para que o cenário seja completo, ele deve descrever o Estímulo (o que inicia a interação), o Ambiente (a situação do sistema durante o estímulo) e a Resposta (a consequência gerada). Por exemplo, um cenário pode ser: "Um usuário remoto solicita um relatório de um banco de dados pela internet durante um período de pico e recebe o relatório em cinco segundos".`,
    'architectural-decision': `Uma Decisão Arquitetural é uma abordagem ou escolha fundamental que o arquiteto toma com o propósito de satisfazer os requisitos arquiteturais do sistema. Essas decisões definem o "como" o sistema será implementado. Elas podem ser baseadas em táticas arquiteturais, que são abordagens conhecidas projetadas para aprimorar um ou mais atributos de qualidade específicos, mas que podem, em contrapartida, prejudicar outros atributos. É essencial que essas decisões sejam registradas, juntamente com os requisitos arquiteturais, atributos de negócio e atributos de qualidade que são afetados, tanto positiva quanto negativamente, e também as decisões alternativas consideradas.`,
    'point-of-view': `O Ponto de Vista arquitetural é o ângulo ou a abordagem sob a qual a arquitetura resultante de um sistema é documentada, sendo uma parte essencial da Síntese Arquitetural. Ele é necessário porque as partes interessadas (stakeholders) têm interesses diferentes no sistema e, portanto, precisam de documentos (representações) que exibam aspectos distintos para atender às suas necessidades específicas de comunicação. Por exemplo, um documento pode ser feito sob o ponto de vista de como os módulos são implementados, o que seria muito útil para os programadores. Uma representação do sistema criada sob um certo ponto de vista é chamada de visão arquitetural.`,
    'architectural-view': `A visão arquitetural é uma representação do sistema feita sob um certo ponto de vista, e é essencial para a Síntese Arquitetural. A arquitetura resultante do sistema é documentada com múltiplas visões arquiteturais para atender às necessidades de comunicação das diversas partes interessadas (stakeholders), que possuem interesses diferentes e precisam de documentos que exibam aspectos distintos do sistema. As visões são importantes porque facilitam o entendimento e a comunicação sobre o sistema, permitem a sua avaliação e auxiliam na tomada de decisões relativas à condução do projeto. Por exemplo, o ponto de vista de Módulos pode gerar uma visão arquitetural utilizando um Diagrama de Classes, enquanto o ponto de vista de Cenários de Uso pode utilizar um Mapa de Navegação ou Diagrama de Sequência.`,
    'intensity-degree': ``,
    'quality-attribute': `Atributos de Qualidade (também conhecidos como Atributos Não-Funcionais) são características do sistema que definem como ele executa suas funções. Exemplos incluem: Performance, Segurança, Confiabilidade, Usabilidade, Manutenibilidade, Escalabilidade, etc.`,
    'business-attribute': `Atributos de Negócio representam aspectos econômicos, comerciais e organizacionais relevantes ao sistema. Exemplos incluem: Custo, Tempo de Entrega, Lucratividade, Competitividade, Conformidade Legal, Sustentabilidade, etc.`,
}
